import type { ScanResult } from "@/types";
import { FINDING_CATALOG } from "@/lib/findings";
import { formatDate } from "@/lib/utils";

export function buildJsonReport(result: ScanResult): string {
  return JSON.stringify(
    {
      product: "Cyfix",
      generatedAt: new Date().toISOString(),
      ...result,
    },
    null,
    2,
  );
}

export function buildMarkdownReport(result: ScanResult): string {
  const failed = result.findings.filter((f) => !f.passed);
  const passed = result.findings.filter((f) => f.passed);

  const lines: string[] = [
    `# Cyfix Security Report`,
    ``,
    `**Domain:** ${result.domain}${result.isDemo ? " _(demo data)_" : ""}`,
    `**Scan started:** ${formatDate(result.startedAt)}`,
    `**Scan finished:** ${formatDate(result.finishedAt)}`,
    `**Security score:** ${result.score} / 100`,
    ``,
    `> Passive checks only — no exploits, brute force, or port scanning were performed. This report reflects a point-in-time snapshot of publicly observable HTTP behavior.`,
    ``,
    `## Findings requiring attention (${failed.length})`,
    ``,
  ];

  if (failed.length === 0) {
    lines.push("_No issues found in this passive scan._", "");
  }

  for (const f of failed) {
    const def = FINDING_CATALOG[f.id];
    lines.push(
      `### [${f.severity.toUpperCase()}] ${f.title}`,
      ``,
      f.description,
      ``,
      `**Impact:** ${f.impact}`,
      ``,
      `**Remediation:** ${def?.remediation ?? ""}`,
      ``,
    );
    if (def?.snippets?.length) {
      for (const s of def.snippets) {
        lines.push(`\`\`\`${s.language}\n${s.code}\n\`\`\``, "");
      }
    }
    if (f.evidence) lines.push(`_Evidence: ${f.evidence}_`, "");
  }

  lines.push(`## Passed checks (${passed.length})`, "");
  for (const f of passed) {
    lines.push(`- ✅ ${f.title}`);
  }

  lines.push("", "---", "_Generated by Cyfix — fix web security with humans and agents together._");

  return lines.join("\n");
}

export function downloadFile(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
